export const GET_PEOPLE_ERROR = 'GET_PEOPLE_ERROR';
export const GET_PEOPLE_LOADING = 'GET_PEOPLE_LOADING';
export const GET_PEOPLE_RESULTS = 'GET_PEOPLE_RESULTS';
export const GET_PEOPLE_COUNT = 'GET_PEOPLE_COUNT';
export const GET_PEOPLE_NEXT = 'GET_PEOPLE_NEXT';
export const GET_PEOPLE_PREVIOUS = 'GET_PEOPLE_PREVIOUS';
